---

- name: Installation apache
  become: yes
  apt:
    name: apache2
    state : present

- name: Démarrer le service apache2
  become: yes
  service:
    name: apache2
    state: started
    enabled: true
