---

- name: Installation pré-requis docker
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - curl
      - python3-pip
    state : present
    update_cache: yes
    cache_valid_time: 3600

- name: Ajout de la clé GPG des dépots docker
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"

- name: Ajout du dépot
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_os_family | lower }} {{ ansible_distribution_release | lower }} stable"
    filename: docker
    state: present

- name: Installation docker community edition
  become: yes
  apt:
    name: docker-ce

- name: Trouver dernière version de docker-compose
  uri:
    url: https://api.github.com/repos/docker/compose/releases/latest
    return_content: true
  register: json_reponse_version_docker_compose

- name: Installation docker-compose
  become: yes
  get_url:
    # url: "{{ json_reponse_version_wpcli.json.assets.0.browser_download_url }}"
    url: "https://github.com/docker/compose/releases/download/{{ json_reponse_version_docker_compose.json.name}}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: a+x

- name: Ajout du compte utilisateur au groupe Docker
  become: yes
  user:
    name: user
    groups: docker
    append: yes

- name: reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta:
    reset_connection
