---

- name: Installation php{{php_version}}
  become: yes
  apt:
    name:
      - php{{php_version}}
      - php{{php_version}}-fpm
    state : present

- name: Démarrer le service php{{php_version}}-fpm
  become: yes
  service:
    name: php{{php_version}}-fpm
    state: started
    enabled: true
